version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: stock-savvy-backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: stock-savvy-frontend
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001/api
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
